# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6220f5cd6ad77073298c647495c1cb77b4660b191dcd4f52e775b3f1efeca6c65251bae4254c39a0a37c63d3e65096cf2747fa41bc299b0d7de9dcbf4940c48

test:
  secret_key_base: a377ee29b95b332ab318c98696dfc191954ba19c7aa05d0181165700e8f011fcc447fe51bdfdc9e53ad1aea940d17728e7d32d4829d5b6d1dc2669ec1b3701d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
